export const WORDS = [
  'JAVASCRIPT',
  'TYPESCRIPT',
  'REACT',
  'NEXTJS',
  'COMPUTADOR',
  'PROGRAMACAO',
  'ALGORITMO',
  'INTERFACE',
  'DESENVOLVIMENTO',
  'FRAMEWORK',
  'BANCODEDADOS',
  'HTML',
  'CSS',
  'PYTHON',
  'JAVA',
  'PHP',
  'RUBY',
  'SWIFT',
  'KOTLIN',
  'GITHUB',
  'RESPONSIVO',
  'FUNCIONAL',
  'VARIAVEL',
  'FUNCAO',
  'OBJETO',
  'ARRAY',
  'STRING',
  'NUMERO',
  'BOOLEANO',
  'CONDICIONAL'
] as const;

export type Word = typeof WORDS[number];